cluster:
   docker-registry:
      domain: 192.168.21.228
      namespace: openpai
      username: admin
      password: Harbor12345
      tag: ctbriv1-20200731
      secret-name: 7bee487bdd6f7e6a074660c80716f1ff
