cluster:
   docker-registry:
      domain: 192.168.24.21
      namespace: openpai
      username: admin
      password: Harbor12345
      tag: ctbriv15-20210721
      secret-name: 7bee487bdd6f7e6a074660c80716f1ff
