---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportal-plugins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportal-plugins
  template:
    metadata:
      labels:
        app: webportal-plugins
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pai-master
                operator: In
                values:
                - "true"
      containers:
      - name: webportal-plugins
        image: 192.168.21.228/openpai/webportal-plugins:v0.17.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webportal-plugins
  name: webportal-plugins-service
  namespace: default
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  selector:
    app: webportal-plugins
  ports:
  - name: webportal-plugins
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32767
