all:
  hosts:
    k8s01:
      ip: 192.168.19.33
      access_ip: 192.168.19.33
      ansible_host: 192.168.19.33
      ansible_ssh_user: root
      ansible_ssh_pass: "Chengshuai1!"
      ansible_become_pass: "Chengshuai1!"
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    k8s01:
      ip: 192.168.19.33
      access_ip: 192.168.19.33
      ansible_host: 192.168.19.33
      ansible_ssh_user: root
      ansible_ssh_pass: "Chengshuai1!"
      ansible_become_pass: "Chengshuai1!"
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    k8s02:
      ip: 192.168.19.34
      access_ip: 192.168.19.34
      ansible_host: 192.168.19.34
      ansible_ssh_user: root
      ansible_ssh_pass: "Chengshuai1!"
      ansible_become_pass: "Chengshuai1!"
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  children:
    kube-master:
      hosts:
        k8s01
    kube-node:
      hosts:
        k8s01:
        k8s01:
        k8s02:
    gpu:
      hosts:
        k8s01:
        k8s02:
    etcd:
      hosts:
        k8s01:
    k8s-cluster:
      children:
        kube-node:
        kube-master:
    calico-rr:
      hosts: {}